export const SHOW_ALL = 'SHOW_ALL';
export const PRODUCT_NAME = 'PRODUCT_NAME';
export const PRODUCT_DESCRIPTION = 'PRODUCT_DESCRIPTION';
export const PRODUCT_MANUFACTURER = 'PRODUCT_MANUFACTURER';
export const PRODUCT_PRICE = 'PRODUCT_PRICE';
export const PRODUCT_QUANTITY = 'QUANTITYPRODUCT_';